<a href="https://colab.research.google.com/github/zamoraricardo15/Udemy---Python-for-Data-Science-and-Machine-Learning-Bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat =  [[1,2,3], [4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.84566604, 0.13940582, 0.83010376, 0.06932738, 0.46447017])

In [22]:
np.random.rand(5,5)

array([[0.2320889 , 0.62335325, 0.93520449, 0.1015218 , 0.97594204],
       [0.51404195, 0.96129934, 0.58060247, 0.49796694, 0.92511775],
       [0.73459175, 0.39950644, 0.16976123, 0.24198528, 0.66529531],
       [0.19171026, 0.21856834, 0.74519303, 0.99855298, 0.50482522],
       [0.86923573, 0.27389742, 0.17566744, 0.35063407, 0.59186483]])

In [23]:
np.random.randn(2)

array([-0.74087184,  0.20288691])

In [24]:
np.random.randn(4,4)

array([[ 2.03021556, -1.58940267,  1.10610887, -0.59717082],
       [-0.45492631, -1.94541262,  0.5660024 ,  1.12404396],
       [-0.62717111,  0.11745638,  0.81156652,  0.03738436],
       [ 1.14369194, -0.67953392,  0.29990855, -0.40256567]])

In [25]:
np.random.randint(1,100)

12

In [27]:
np.random.randint(1,100,100)

array([48, 84, 34, 16, 10,  4, 95, 56, 82, 75, 29, 86,  1, 10,  9, 30, 46,
       74, 49, 75, 37, 70, 14, 38, 26, 10, 42,  2, 97, 26, 34, 30, 23, 70,
       60, 14, 76, 15, 77, 59, 64, 81, 53, 32, 73,  2, 75, 76, 17, 75,  1,
       87, 89, 96, 38, 20, 84, 45,  8, 28, 29, 98, 93,  4, 33, 30, 63, 21,
       11, 14, 78, 24, 71, 13, 41, 88, 25, 80, 91,  6,  2, 57, 20, 22, 22,
       21, 17, 26, 19, 18, 95, 91, 18, 91, 90, 57, 40, 31, 88, 82])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([27,  3, 34, 26, 49, 45, 13, 35,  1, 33])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

49

In [35]:
ranarr.min()

1

In [36]:
ranarr

array([27,  3, 34, 26, 49, 45, 13, 35,  1, 33])

In [37]:
ranarr.argmax()

4

In [38]:
ranarr.argmin()

8

In [39]:
arr.shape

(25,)

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int64')

In [46]:
from numpy.random import randint

In [47]:
randint(2,10)

9

In [48]:
#Numpy Indexing and Selection

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[1]

1

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[0:5] = 100

In [62]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]

In [67]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [68]:
slice_of_arr[:] = 99

In [69]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy = arr.copy()


In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy[:] = 100

In [75]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [76]:
arr_2d = np.array([[5,10,15], [20,25,30], [30,40,45]])

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [79]:
arr_2d[2][1]

40

In [80]:
arr_2d[1,2]

30

In [81]:
arr_2d[1][2]

30

In [82]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [83]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
##Conditional Selection

In [85]:
arr=np.arange(1,11)

In [86]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
bool_arr = arr > 5

In [89]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [91]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [92]:
arr[arr<3]

array([1, 2])

In [93]:
arr_2d = np.arange(50).reshape(5,10)

In [94]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
arr_2d[1:3, ]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [98]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [99]:
#Numpy Operations

In [101]:
arr = np.arange(0,11)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [104]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [107]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [108]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [110]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [112]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [113]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [114]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [115]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [116]:
np.max(arr)

10

In [117]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [118]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])